name: Sync Fork

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: sky2016cn/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}        
          owner: cmliu
          head: main
          base: main
