name: Sync Fork

on:
  schedule:
    - cron: '*/3 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: sky2016cn/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: cmliu
          base: main
          head: main
